[package]
name = "ekim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel_cli = "2.1.1"
dotenv = "0.15.0"
rocket = "0.5.0-rc.3"
